### PR TITLE
Use gradient technique to depth-init snapping buffers

### PR DESCRIPTION
**Pull request by tmarti**
Solves https://github.com/xeokit/xeokit-sdk/issues/1162

### CODE REVIEW

**Comment by xeolabs** [comment]
> Still, some problems with the following example page:
> 
> ```
> examples/scenemodel/snapToVertex_dtx_instancing_triangles.html
> ```
> 
> Will keep digging here

Nice one @tmarti - how's it looking with the other snapping examples? Worth merging at this point, or would you like to refine more?

**Comment by tmarti** [comment]
Can you please answer with a link to the other examples?

**Comment by tmarti** [comment]
But yes, should be safe to merge, and maybe @Kurtil (the OP) you can confirm it solves the problems you were observing 🙂

**Comment by xeolabs** [comment]
> Can you please answer with a link to the other examples?

Scroll down to "Snap Picking" for a complete set of tests for snapping:

https://xeokit.github.io/xeokit-sdk/examples/scenemodel/

**Comment by xeolabs** [comment]
> Still, some problems with the following example page:
> 
> ```
> examples/scenemodel/snapToVertex_dtx_instancing_triangles.html
> ```
> 
> Will keep digging here

Note that the same issue also happens in master, prior to merging this PR, so is not caused by this PR. Therefore, I'll merge.

Could it somehow be related to triangle edges that are only adjacent to a single triangle?

[Screencast from 25.10.2023 22:50:07.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/fa4244dc-0ab5-4882-8ede-558f3d629484)

**Comment by tmarti** [comment]
> Wondering, could it somehow be related to triangle edges that are only adjacent to a single triangle?

It indeed looks like that’s the case. Might need to debug a bit that shader.

**Comment by tmarti** [comment]
@xeolabs, would you see with good eyes introducing @Kurtil's snapping-buffer-debugger code somehow hidden under a toggle?

Of course always disabled by default, but think it would be really nice to keep his precious "visual debugger" in case there are problems again in the future with snapping 🙂.

It could come disabled by default and maybe (not necessarily this way, just an example):

```js
const v = new Viewer({ 
    // ...
    debugOptions: {
        showSnapBufferInspector: true|false, // default false
    }
});
```

**Pull request merged**
