### PR TITLE
WIP: [DataTextures]: snap-to-vertex functionality

### PR DESCRIPTION
**Pull request by tmarti**
WIP; will update the description when it's complete and working

(The functionality will be 100% based on GPU rendering; no JS-side processing of the geometry or nearest searches)

### CODE REVIEW

**Comment by pbbr** [comment]
@tmarti Very nice work, looks fantastic! 

Is it possible to port the renderer to the [VBOSceneModel](https://github.com/xeokit/xeokit-sdk/tree/master/src/viewer/scene/models/VBOSceneModel) (especially the [trianglesBatching](https://github.com/xeokit/xeokit-sdk/tree/a02bf9d4f31e7e7572457081d4d2296d06b1a4fe/src/viewer/scene/models/VBOSceneModel/lib/layers/trianglesBatching) layer)? Would be perfect, thanks a lot for your work!

**Comment by xeolabs** [comment]
@pbbr unfortunately not, because DataTextureSceneModel and VBOSceneModel both fully encapsulate their own shaders and rendering logic.

**Comment by pbbr** [comment]
@xeolabs I understand. But it should be easy to write this two renderer (TrianglesVertexDepthRenderer and TrianglesSnapPickZBufferInitializer) also for VBOSceneModel? Or what am I missing?

**Comment by xeolabs** [comment]
@pbbr Yes, it's likely we'll do that. Didn't understand that you mean't just the vertex snap shaders.

**Comment by pbbr** [comment]
@xeolabs This are great news. Can't wait to have the vertex snap shaders available for VBOSceneModel. Thx!

**Comment by tmarti** [comment]
@xeolabs TLDR; you don't need normals for your VBO case 🎉 

## Explanation

Oh, just forget about normals in that shader you link for data-tex 🙂.

It is a feature of data-tex the possibility to render both single-sided and double-sided geometry in same gl.draw* call. For that purpose (double-sided case), the normal is needed just to detect if the triangle is facing the camera, and if not reverse the order the 3 vertices are emitted to the Fragment Shader so it is "always seen" according to backface culling.

So you don't need that becase you don't target data-tex now 🙂; instead in the VBO case you already have separate layers for single-sided (solid case) and double sided (non-solid case). I think in that case you were just invoking the double-sided renders disabling gl-backface-culling plus the single-sided renderers with enabling backface-culling.

You can just keep doing the same in the renderer you're porting to VBO, and for that normals are not needed 👍

**Comment by tmarti** [comment]
See here the technical explanation on how snapping works in this PR:
- https://github.com/tmarti/graphics-research/blob/main/articles/webgl2-gpu-based-snapping.md

**Comment by pbbr** [comment]
@xeolabs We saw that you meanwhile have integrated the vertex snap shaders in the VBOSceneModel - very well done!

What we saw for the batching layers is that both the vertex and edge snapping aren't working as expected. The vertex snapping isn't working at all (see also https://xeokit.github.io/xeokit-sdk/examples/picking/#snapToVertex). The edge snapping seems to work but detect also hidden edges (of the same as well as other objects) that leads to strange behaviors. Also the SnapBatchingDepthBufInitRenderer seems to disturb the SnapBatchingDepthRenderer. Do you have any idea how to solve this?

**Comment by xeolabs** [comment]
Yip this is one of the last fixes before the release, aiming to fix this next week. 

I decided to publish the live examples for this as a test reference in the meantime, so effectively they are "visibly failing tests".

It shouldn't be hard to fix - just some small thing that differs from the data texture snapping shaders that we need to track down.

**Comment by xeolabs** [comment]
@pbbr is the example at  https://xeokit.github.io/xeokit-sdk/examples/picking/#snapToVertex not working for you? 

Note that it's just set up for mouse pointer input at the moment - works OK on my machine, but let me know if you're getting issues with that..

[Screencast from 02.09.2023 12:40:05.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/d37ac9fb-9a68-4eca-b308-cd52c9815ff0)

**Comment by tmarti** [comment]
A fix for this in on the way 🙂

**Comment by xeolabs** [comment]
And .. now built and deployed to examples, thanks for the fixes @tmarti!

* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_instancing_triangles
* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_batching_triangles

[Screencast from 02.09.2023 18:57:31.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/11755603-bd50-4916-a829-3b41f7a270eb)

\ping @pbbr

**Comment by xeolabs** [comment]
Just an FYI that I've discovered an issue with snapping for the case of SceneModels loaded from XKT, and have just found a fix for that. 

So don't worry if you find an issue with snapping for models like Duplex etc - I'll commit my fix for that tomorrow.

**Comment by xeolabs** [comment]
Snapping now fixed for VBO batching/instancing layers.

**Comment by pbbr** [comment]
> 

@xeolabs Thanks for the quick fix! 

The edge snapping works now as expected. Unfortunately, the vertex snapping not in this example https://xeokit.github.io/xeokit-sdk/examples/picking/#snapToVertex and the other examples (we tried Firefox, Edge and Chrome on Windows). On Safari it works :-) Any idea why?

**Comment by xeolabs** [comment]
@pbbr no probs! I don't have a Windows computer unfortunately, so unable to debug on my end at the moment. Any errors in the console?

**Comment by xeolabs** [comment]
How about edge snapping - does this work on Windows?
https://xeokit.github.io/xeokit-sdk/examples/picking/#snapToEdge

**Comment by pbbr** [comment]
@xeolabs Yes, this works on Windows.

**Comment by pbbr** [comment]
@xeolabs On Edge for Mac everything works. We tried on different Windows machines with no success.

**Comment by pbbr** [comment]
@xeolabs Did you find the root cause for this behaviour?

PS: To improve the picking speed, I would propse to add the pick element offset and count also to the snap pick renderer (as for the existing pick renderer, see https://github.com/xeokit/xeokit-sdk/blob/a0817adf8c40556a4cbabebc563cb19fa625a0cf/src/viewer/scene/webgl/Renderer.js#L1163)

**Comment by xeolabs** [comment]
@pbbr I haven't looked at it yet - don't have a windows machine available at the moment unfortunately. I'll take a look through the shaders though and see if anything looks obvious in the meantime. Can you see any errors in the console? 

> PS: To improve the picking speed, I would propse to add the pick element offset and count also to the snap pick renderer (as or the existing pick renderer: https://github.com/xeokit/xeokit-sdk/pull/1078)

Yeah that's good idea.

**Comment by xeolabs** [comment]
@pbbr time to roll out the low-level test examples.. could you please test which of these fail on Windows:

* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_instancing_triangles
* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_batching_triangles
* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToEdge_vbo_instancing_triangles
* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToEdge_vbo_batching_triangles

**Comment by pbbr** [comment]
@xeolabs The vertex snapping fails (1 & 2), the edge snapping works (3 & 4).

**Comment by xeolabs** [comment]
Tentatively, we may have a fix - I just tried this fix for  (1) on Win10 and Chrome on BrowserStack - looks to be working over there.

[Screencast from 07.09.2023 22:22:19.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/125167c0-69f3-4b47-8fe7-572e4ea6979a)

**Comment by xeolabs** [comment]
@pbbr Could you try the vertex snapping examples on Windows again?

**Comment by pbbr** [comment]
@xeolabs Looks good! Vertex snapping is now working also on Windows, well done.

**Comment by pbbr** [comment]
@xeolabs We've found another "issue". If there is some distance to an object, hidden edges and vertices are also detected by snap-in pick. Distance seems to be in correlation to the object size. Do you have an idea why this happens?

https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_instancing_triangles

image

**Comment by xeolabs** [comment]
@pbbr Likely to be a loss of precision within the depth buffer, related to this [magic number](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/model/vbo/snapInstancing/SnapInstancingDepthBufInitRenderer.js#L286) in the depth buffer initialization shaders. At large distances, the effect of this offset is likely to lose the precision required to properly cause visible surfaces to occlude the invisible ones.

I don't have a solution at this stage, however a solution could involve something similar to the [logarithmic depth buffer](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/model/vbo/snapInstancing/SnapInstancingDepthBufInitRenderer.js#L344).

**Comment by xeolabs** [comment]
@pbbr It seems that enabling the Viewer's logarithmic depth buffer fixes this issue:

````javascript
    const viewer = new Viewer({
        canvasId: "myCanvas",
        logarithmicDepthBufferEnabled: true
    });
````

https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#snapToVertex_vbo_instancing_triangles

[Screencast from 13.09.2023 05:41:28.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/00fe125e-6a7c-4ea2-b3f7-725fa4a31fc9)

**Comment by pbbr** [comment]
@xeolabs Nice hint, this solves the problem perfectly!

**Comment by pbbr** [comment]
@xeolabs An additional thing we saw is the missing recognition of "inner" edges (plane to plane < 90°). There, the edge seems to be recognized as it is on the backface and thus no picking is possible. On the backside, the picking works. Do have an idea how to improve this?

**Comment by tmarti** [comment]
@pbbr can you show an annotated screenshot of this? Just to exactly visualize the problem 🙂

> we saw [...] the missing recognition of "inner" edges (plane to plane < 90°). There, [...] no picking is possible.

**Pull request merged**
