### PR TITLE
Set up the env to run XKTLoaderPlugin in headless mode

### PR DESCRIPTION
**Pull request by qs-wang**
setup babel, jest, webgl-canvas mock, and etc. For now it is possible to run the test, and loading the performance model with jest test cases

### CODE REVIEW

**Review by xeolabs — APPROVED** [review]

**Comment by jenbuzz** [comment]
@xeolabs @qs-wang a gitignore file was merged in this PR and it seems a little too aggresive (and a little too vuejs related). The dist folder is now ignored. Is this on purpose?

**Comment by qs-wang** [comment]
copied from GitHub's node gitignore file. What's our practice here? Do we want to include dist folder?

**Comment by xeolabs** [comment]
@qs-wang @jenbuzz we do want to include the dist directory, yes

**Comment by qs-wang** [comment]
@xeolabs anything else I should remove from gitignore file? I can create another PR for this.

**Comment by xeolabs** [comment]
@qs-wang I think just removing dist is fine as far as I can tell - yes please, another PR

**Pull request merged**
