### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by mlankamp**
Typings available for:
- [x] Viewer
- [x] Scene
- [x] Camera
- [x] metadata
- [x] AngleMeasurementsPlugin
- [x] AnnotationsPlugin
- [x] AxisGizmoPlugin
- [x] BCFViewpointsPlugin
- [x] CityJSONLoaderPlugin
- [x] DistanceMeasurementsPlugin
- [x] FastNavPlugin
- [x] GLTFLoaderPlugin
- [x] LASLoaderPlugin
- [x] NavCubePlugin
- [x] OBJLoaderPlugin
- [x] SectionPlanesPlugin
- [x] SkyboxesPlugin
- [x] STLLoaderPlugin
- [x] StoreyViewsPlugin
- [x] TreeViewPlugin
- [x] ViewCullPlugin
- [x] WebIFCLoaderPlugin
- [x] XKTLoaderPlugin
- [x] XML3DLoaderPlugin
- [x] ContextMenu

Partial typings:
- [x] math

### CODE REVIEW

**Comment by xeolabs** [comment]
Looking good! BTW at some point we could add typedoc, like we're using in [xeokit-webgpu-sdk](https://github.com/xeokit/xeokit-webgpu-sdk)

**Comment by mlankamp** [comment]
@xeolabs i'm ready for now, as a first version of the typing this seems ok. Will keep working on adding new typings.

**Comment by mlankamp** [comment]
> Looking good! BTW at some point we could add typedoc, like we're using in [xeokit-webgpu-sdk](https://github.com/xeokit/xeokit-webgpu-sdk)

I'm unable to view that repo, can you allow me access?

**Comment by mlankamp** [comment]
Thank you! Can we create a new beta ```2.2.5-beta-2```?

**Comment by xeolabs** [comment]
I've just published ````@xeokit/xeokit-sdk@2.2.5-beta-2```` to npm with this PR. Thanks!

**Pull request merged**
