### PR TITLE
Throws when one try to create a scene with an unused mesh during finalize.

### PR DESCRIPTION
**Pull request by paireks**
I tried to implement easiest fix of this issue: https://github.com/xeokit/xeokit-sdk/issues/1336

Please have a look at that proposal and give me hints if I got something wrong.
When someone tries to create a mesh that is later not used -> error should be thrown during finalize.
It's a quite big change of existing behaviour.

### CODE REVIEW

**Comment by xeolabs** [comment]
Thanks - let me think about this one for a bit though - throwing an exception is a bit brutal. It might actually be a better to create dummy entities for those meshes, with object:false.

**Comment by paireks** [comment]
Sure, but should we create these dummy entities during finalize?

**Comment by paireks** [comment]
Or maybe there is some other way to inform the user inside viewer or console about the issue, without throwing an exception?

**Comment by xeolabs** [comment]
> Or maybe there is some other way to inform the user inside viewer or console about the issue, without throwing an exception?

Perhaps both creating the entities in finalize() and at the same time logging a warning to the console.

**Comment by xeolabs** [comment]
Actually, it may be practical to defer the creation of meshes until their entities are created - see here: https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/model/SceneModel.js#L3050

The mesh parameters could be cached, and then SceneModel._createMesh() called to create the mesh within SceneModel.createEntity() only once the Entity refers to it.

**Comment by xeolabs** [comment]
In that code, we're creating the mesh immediately at the end of SceneModel.createMesh(), but that `cfg` passed to `_createMesh` could be stored in a map against the mesh ID, then SceneModel.createEnity() could get that from the map and call  `_createMesh` with it.

**Comment by paireks** [comment]
If I understand it correctly, you'd like to postpone mesh creation, which makes sense to me, but it would also be probably a breaking change, as SceneModel.createMesh() already returns an instantly created mesh.

**Comment by xeolabs** [comment]
> If I understand it correctly, you'd like to postpone mesh creation, which makes sense to me, but it would also be probably a breaking change, as SceneModel.createMesh() already returns an instantly created mesh.

Yes, and actually this API change would be OK, because nothing outside of SceneModel ever uses those returned SceneMeshes - they are only used by SceneObjects. I just made createMesh() return a SceneMesh to make testing easier, and for symmetry. It would be fine to make that method return nothing.

**Comment by paireks** [comment]
Ok, so here is mesh creation deferring. I attached comment for each line in deferring part as it is a bit more tricky, but I can remove it any time.
Let me know if I got something wrong.
Also I return true/false for createMesh(), but can return nothing if it's preferred.

**Comment by paireks** [comment]
I will update types part after this part will be accepted.

**Comment by xeolabs** [comment]
Looks good to me @paireks, thanks

**Comment by xeolabs** [comment]
Published in 2.5.2-beta-7 🙏

**Pull request merged**
