### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by Amoki**

### CODE REVIEW

**Comment by xeolabs** [comment]
Looks like you'll need to merge/rebase @tmarti

**Comment by tmarti** [comment]
No problem @xeolabs, just let me know when this one is merged 👍 

I did the last rebase just around 13hrs ago, and this one will probably not have conflicts so be a quick one

**Comment by xeolabs** [comment]
Cool - I have these two errors doing an `npm run build`:

Error: Could not resolve '../../viewer.js' from src/plugins/WebIFCLoaderPlugin/WebIFCLoaderPlugin.js
Error: Could not resolve '../../viewer/scene/LineSet.js' from src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js

**Comment by Amoki** [comment]
Are you on the latest version? I fixed them
https://github.com/xeokit/xeokit-sdk/pull/1015/files#diff-3a561a1b3ab149f09bcff1453d4f3c144bf5c92d8f4462d895f7e88846aa7143R8
https://github.com/xeokit/xeokit-sdk/pull/1015/files#diff-3a561a1b3ab149f09bcff1453d4f3c144bf5c92d8f4462d895f7e88846aa7143R8

**Comment by tmarti** [comment]
Ok, pushed a fix to data-tex branch, building again 👍

**Pull request merged**
