### PR TITLE
1 x 1 picking viewport

### PR DESCRIPTION
**Pull request by Kurtil**
Picking with a 1 x 1 viewport. I used the clip position remapping method used by @tmarti for the snap picking.

WARNING : ray picking is broken and needs to be fixed before merging this PR! :(

Before :

rayPickSurface-before

After (with this PR merged) :

rayPickSurface-after

It seems the before is not perfectly accurate. Maybe these changes accentuate the small inaccuracies...

### CODE REVIEW

**Comment by Kurtil** [comment]
Ray picking precision issue https://github.com/xeokit/xeokit-sdk/issues/1105.

**Comment by xeolabs** [comment]
@Kurtil is BIMData depending on ray-picking functionality (with origin->ray) ? I don't even know of any users who are actually depending on ray-picking, so if that can't be fixed, I'd be in favour of removing ray-picking altogether, if that stands in the way of faster surface picking with canvas coordinates (enabled by this PR). Fast model interaction is always our top priority (and canvas surface picking is a big part of that, since it's used by camera interaction).

**Comment by xeolabs** [comment]
@Kurtil I've fixed the precision issue while doing a merge conflict fix: https://github.com/xeokit/xeokit-sdk/pull/1168/commits/e9549ca02df787e444831ed1d2f5e2722ac887c9

**Comment by tmarti** [comment]
@xeolabs at Tribia we're also depending on ray picking for laser mesurements, plus some custom functionalities for obtaining the ifc-storey and ifc-space where the camera is! 🙂

**Pull request merged**
